# Generated by Django 5.1 on 2024-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
