# Generated by Django 5.1 on 2024-09-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='documents/id_proof/')),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='documents/address_proof/')),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='documents/photos/')),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to='documents/education/')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='documents/education/')),
                ('professional_certifications', models.FileField(blank=True, null=True, upload_to='documents/certifications/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='documents/employment/')),
                ('relieving_letter', models.FileField(blank=True, null=True, upload_to='documents/employment/')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='documents/employment/')),
                ('pay_slip', models.FileField(blank=True, null=True, upload_to='documents/employment/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='documents/tax/')),
                ('tax_documents', models.FileField(blank=True, null=True, upload_to='documents/tax/')),
                ('bank_details', models.FileField(blank=True, null=True, upload_to='documents/bank/')),
                ('police_verification', models.FileField(blank=True, null=True, upload_to='documents/compliance/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='documents/medical/')),
                ('reference_letter', models.FileField(blank=True, null=True, upload_to='documents/references/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='documents/others/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='emp.employee')),
            ],
        ),
    ]
