# Generated by Django 5.1 on 2024-09-12 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_employee_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_description', models.CharField(max_length=500)),
                ('asset_image', models.ImageField(upload_to='asset_images/')),
                ('present', models.BooleanField(default=True)),
                ('date_assigned', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='emp.employee')),
            ],
        ),
    ]
