# Generated by Django 5.1 on 2024-09-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_slip', models.FileField(upload_to='salary_slips/')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='emp.employee')),
            ],
        ),
    ]
