# Generated by Django 5.1 on 2024-09-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_alter_project_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='if_media',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_assigned_task',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks', to='emp.employee'),
        ),
    ]
