# Generated by Django 5.1.1 on 2024-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0015_banks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='upi_qr',
            field=models.FileField(blank=True, null=True, upload_to='upi_qr/'),
        ),
    ]
