# Generated by Django 5.1.1 on 2024-09-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0016_alter_banks_upi_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='upi_qr',
        ),
    ]
