# Generated by Django 5.1.1 on 2024-09-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0018_sendslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendslip',
            name='payment_method',
            field=models.CharField(choices=[('paytm', 'paytm'), ('phone_pe', 'phone_pe'), ('net_banking', 'net_banking'), ('others', 'others')], default='paytm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sendslip',
            name='present_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sendslip',
            name='status',
            field=models.CharField(default='Paid', max_length=100, null=True),
        ),
    ]
