# Generated by Django 5.1.1 on 2024-09-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0020_sendslip_payment_shot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendslip',
            name='payment_shot',
        ),
    ]
