# Generated by Django 5.1.1 on 2024-09-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0021_remove_sendslip_payment_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
